### ISSUE TITLE
Workaround for double-conversion bug incompatible with cabal-dev ghci

### ISSUE THREAD

**Issue by gimbo** [bos/blaze-textual#4]
`README.md` suggests that a workaround for the `double-conversion` `ghci` bug is to install `blaze-textual` with the `-fnative` flag and then reinstall `aeson`.  I've been trying to get this to work with `cabal-dev` today, with no success.

I'm working on the assumption that `cabal-dev --cabal-install-arg=-fnative install` will pass the `native` flag to every `cabal install` call, including the one for `blaze-textual`.  (?)  (I've also tried `cabal-dev install --cabal-install-arg=-fnative` in case order matters, and just plain old `cabal-dev install -fnative` as the docstring for `--cabal-install-arg` suggests that should work.)

Assuming that's true, then, well, it's not working.  I've tested by creating a package which depends only on `base` and `aeson`, running the above command on it to create a sandbox, then running `cabal-dev ghci` to get a `ghci` session in that sandbox.  This fails, with the usual double-conversion problem...

```
Loading package double-conversion-0.2.0.1 ... <command line>: can't load .so/.DLL for: stdc++ (dlopen(libstdc++.dylib, 9): image not found)
```

One thing I've noticed, outside the `cabal-dev` context, may be relevant here.   It seems (but I confess I didn't test this exhaustively) that the `-fnative` advice doesn't work with a clean install.  That is (it seems), if `aeson` isn't already installed when you `cabal-install -fnative`, then when you subsequently `cabal install --reinstall aeson`, `cabal` also reinstalls `blaze-textual` and `double-conversion` and the bug returns.  Having done that, if you repeat the process (ie starting with `aeson` installed, if effectively broken), the fix seems to work.  This could explain why `cabal-dev` is having this problem, as it is effectively creating a clean install in the sandbox.  Why `cabal install` works this way is beyond me - the dependencies are there so why reinstall them? - but there you go.

Or maybe I've just got it wrong and `-fnative` isn't being passed through to `cabal install`...  Or something else...?

So... Any idea how to work around _this_?

**Comment by bos** [comment]
I've made `-fnative` the default for now, because it was just too painful.

Sorry for the inconvenience!
